<a href="https://colab.research.google.com/github/YehorChykin/HW_DS/blob/main/HW_DS_M4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [5]:
m = np.zeros((3, 4), dtype=int)
print(m)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [6]:
c = np.random.randint(1, 11, size=(5,5))
print(c)

[[10  2  5  9  6]
 [ 6  7  1  8  7]
 [ 5  5  7  8  9]
 [ 8  5  1  6  3]
 [ 6  8 10  6  2]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [7]:
np.random.rand(4,4)

array([[0.07426945, 0.40330083, 0.67858694, 0.75423274],
       [0.19156834, 0.40066372, 0.85810437, 0.42630144],
       [0.75537746, 0.53208893, 0.90933631, 0.01595063],
       [0.03447129, 0.23365728, 0.80190997, 0.2321283 ]])

5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [15]:
m1 = np.random.randint(1,11,5)
m2 = np.random.randint(1,11,5)
print(m1)
print(m2)
print(m1+m2)
print(m1-m2)
print(m1*m2)

[ 9  8 10 10  6]
[5 7 3 3 5]
[14 15 13 13 11]
[4 1 7 7 1]
[45 56 30 30 30]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [16]:
m1 = np.random.randint(1,11,7)
m2 = np.random.randint(1,11,7)

np.dot(m1,m2)

128

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [22]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,3))
print(a)
print(b)
c = np.dot(a, b)
print(c)

[[7 8]
 [5 7]]
[[ 9  1  6]
 [ 6 10  5]]
[[111  87  82]
 [ 87  75  65]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [27]:
a = np.random.randint(1,11, size=(3,3))
print(a)
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 3  7  1]
 [ 9  3  5]
 [ 5 10  3]]
[[ 0.66129032  0.17741935 -0.51612903]
 [ 0.03225806 -0.06451613  0.09677419]
 [-1.20967742 -0.08064516  0.87096774]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [29]:
a = np.random.randint(1,11, size=(4,4))
print(a)
a.T

[[ 5  4  5  7]
 [ 5  8  5  3]
 [10  7  8  9]
 [ 6  9  9  5]]


array([[ 5,  5, 10,  6],
       [ 4,  8,  7,  9],
       [ 5,  5,  8,  9],
       [ 7,  3,  9,  5]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [31]:
a = np.random.randint(1,11, size=(3,4))
b = np.random.randint(1, 11, size=4)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 5  2  7  6]
 [ 6  7  3 10]
 [ 2  8  7  9]]
[10  9 10  8]
[186 233 234]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [33]:
a = np.random.randint(1,11, size=(2,3))
b = np.random.randint(1, 11, size=3)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 7 10  6]
 [ 5  3  9]]
[ 7  3 10]
[139 134]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [35]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
print(a)
print(b)
print(np.multiply(a,b))

[[4 9]
 [4 1]]
[[7 7]
 [4 5]]
[[28 63]
 [16  5]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [38]:
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
print(a)
print(b)
print(np.dot(a, b))

[[6 5]
 [1 5]]
[[ 5  1]
 [10  1]]
[[80 11]
 [55  6]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [37]:
a = np.random.randint(1,101, size=(5,5))
print(a)
print(a.sum())

[[67 69 47 25 84]
 [66 47 37 44  1]
 [67 71 51 89 59]
 [49 50  7 56 69]
 [49 13 50 98 34]]
1299


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [45]:
a = np.random.randint(1,11, size=(4,4))
b = np.random.randint(1,11, size=(4,4))
print(a)
print(b)
print(a-b)

[[ 7  8  9  8]
 [ 4  4  2  5]
 [ 5  8 10  3]
 [ 9  6  4  6]]
[[10  6 10  9]
 [ 4  7  9 10]
 [ 8  8  2  7]
 [ 6  4  8  2]]
[[-3  2 -1 -1]
 [ 0 -3 -7 -5]
 [-3  0  8 -4]
 [ 3  2 -4  4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [44]:
a = np.random.rand(3,3)
print(a)
s = np.sum(a, axis=1)
print(s)
v = s.reshape(-1, 1)
print(v)

[[0.63008415 0.92054127 0.80142268]
 [0.18565557 0.85778452 0.84866704]
 [0.55742155 0.3758135  0.16982963]]
[2.35204809 1.89210713 1.10306468]
[[2.35204809]
 [1.89210713]
 [1.10306468]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [46]:
a = np.random.randint(1,11, size=(3,4))
print(a)
akv = np.square(a)
print(akv)


[[ 9  4  3  6]
 [ 5  5  4  3]
 [ 4  2 10  3]]
[[ 81  16   9  36]
 [ 25  25  16   9]
 [ 16   4 100   9]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [48]:
v = np.random.randint(1, 51, size=4)
print(v)
vkor = np.sqrt(v)
print(vkor)

[18  3 14 24]
[4.24264069 1.73205081 3.74165739 4.89897949]
